- name: copy nginx package to remote host
  copy: src=nginx-1.16.0.tar.gz dest=/usr/local/src/nginx-1.16.0.tar.gz
  tags: cppkg
- name: tar nginx
  shell: cd /usr/local/src;tar -xf nginx-1.16.0.tar.gz
- name: install pakger
  yum: name={{item}} state=latest
  with_items: 
  - openssl-devel
  - pcre-devel
  - gcc
  tags: dpdpkg
- name: useradd nginx
  shell: useradd nginx
  tags: add_nginx
- name: install nginx
  shell: cd /usr/local/src/nginx-1.16.0;./configure --user=nginx --group=nginx --prefix=/usr/local/nginx --with-http_stub_status_module --with-http_ssl_module --with-pcre;make && make install
  tags: inngx
- name: copy start config
  template: src=nginx.service dest=/usr/lib/systemd/system/nginx.service
  notify: start nginx
- name: mkdir vhosts
  shell: mkdir /usr/local/nginx/vhosts
- name: copy index.html
  template: src=index.html dest=/usr/local/nginx/html/index.html
- name: copy config file nginx.conf
  template: src=nginx.conf dest=/usr/local/nginx/conf/nginx.conf
  notify: reload nginx service

